/* copy-fonts.js - run once on the coordinator laptop:   node tools/copy-fonts.js
   The site's headings/body text use the "Inter" font. If it is installed on this laptop it looks right here,
   but the lab computers do not have it. This script finds Inter on this laptop and copies it into
   public/assets/fonts/ so the server sends it to every computer. (JetBrains Mono and Outfit are already bundled.) */
const fs = require('fs'), path = require('path'), os = require('os');
const OUT = path.join(__dirname, '..', 'public', 'assets', 'fonts');
const home = os.homedir();
const roots = [
  path.join(home, '.fonts'), path.join(home, '.local', 'share', 'fonts'), '/usr/share/fonts', '/usr/local/share/fonts',
  '/Library/Fonts', path.join(home, 'Library', 'Fonts'), '/System/Library/Fonts',
  'C:\\Windows\\Fonts', path.join(process.env.LOCALAPPDATA || '', 'Microsoft', 'Windows', 'Fonts'),
  process.argv[2] || ''
].filter(Boolean);
const found = [];
function walk(d, depth = 0) {
  if (depth > 6) return;
  let ents; try { ents = fs.readdirSync(d, { withFileTypes: true }); } catch { return; }
  for (const e of ents) {
    const p = path.join(d, e.name);
    if (e.isDirectory()) walk(p, depth + 1);
    else if (/^inter/i.test(e.name) && /\.(ttf|otf|woff2?)$/i.test(e.name) && !/display|italic|tight|mono/i.test(e.name)) found.push(p);
  }
}
roots.forEach(r => walk(r));
if (!found.length) {
  console.log('Inter was not found on this computer, so nothing was copied.');
  console.log('Fix: download Inter (https://rsms.me/inter/) and run:  node tools/copy-fonts.js <folder-with-the-font-files>');
  process.exit(0);
}
fs.mkdirSync(OUT, { recursive: true });
const fmt = f => ({ '.ttf': 'truetype', '.otf': 'opentype', '.woff': 'woff', '.woff2': 'woff2' })[path.extname(f).toLowerCase()];
const weights = { thin: 100, extralight: 200, light: 300, regular: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800, black: 900 };
let css = '/* generated by tools/copy-fonts.js */\n';
const variable = found.find(f => /variable|\[/i.test(path.basename(f)));
if (variable) {
  const n = 'inter-variable' + path.extname(variable).toLowerCase();
  fs.copyFileSync(variable, path.join(OUT, n));
  css += `@font-face{font-family:'Inter';font-weight:100 900;font-style:normal;font-display:block;src:url('/assets/fonts/${n}') format('${fmt(variable)}')}\n`;
  console.log('Copied variable font:', variable);
} else {
  const done = new Set();
  for (const f of found) {
    const base = path.basename(f).toLowerCase().replace(/\.[a-z0-9]+$/, '');
    const key = Object.keys(weights).find(k => base === 'inter-' + k || base === 'inter' + k) || (base === 'inter' ? 'regular' : null);
    if (!key || done.has(key)) continue;
    done.add(key);
    const n = `inter-${key}` + path.extname(f).toLowerCase();
    fs.copyFileSync(f, path.join(OUT, n));
    css += `@font-face{font-family:'Inter';font-weight:${weights[key]};font-style:normal;font-display:block;src:url('/assets/fonts/${n}') format('${fmt(f)}')}\n`;
    console.log('Copied', f);
  }
  if (!done.size) { console.log('Found Inter files but not in a recognised style (Regular/Bold...).'); process.exit(0); }
}
fs.writeFileSync(path.join(OUT, 'fonts-inter.css'), css);
console.log('\nDone. Restart the server and hard-refresh the lab computers (Ctrl+F5).');
